# Site Settings
baseurl: 

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
blog: False
people: False

# Language of the website
lang: en

# Search engine optimization settings
title: Alessandro Flaborea
tagline: Department of Computer Science, Sapienza University of Rome, Italy

description: PhD student in computer science at the Sapienza University of Rome, where I am also a member of the Perception and Intelligence lab (PINlab). My research focuses on artificial intelligence and computer vision, and I am particularly interested in topics such as pose forecasting, anomaly detection, few-shot learning, and geometric deep learning. I am excited to work in these cutting-edge areas of computer science, and I look forward to making significant contributions to the field through my research
author: Alessandro Flaborea
twitter:
  username: AleFlaborea
  card: Alessandro Flaborea
logo: assets/img/cv.jpg
social:
  name: aleflabo
  links:
    - https://github.com/aleflabo
    - https://www.instagram.com/aleflabo/
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS
  presentation_text: "I am a PhD student in computer science at the Sapienza University of Rome, where I am also a member of the Perception and Intelligence lab (PINlab). My research focuses on artificial intelligence and computer vision, and I am particularly interested in topics such as pose forecasting, anomaly detection, few-shot learning, and geometric deep learning. I am excited to work in these cutting-edge areas of computer science, and I look forward to making significant contributions to the field through my research."


# Pagination
# paginate: 5
# paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
